Feat/backend interaction
MoViDe-Project/motis pull request #10
Opened 2024-12-19 14:20 UTC by Kvnstrck

closes #3

2024-12-19 14:36 UTC, nicosvv approved these changes

2024-12-19 14:49 UTC, D3vZro requested changes
PR title does not conform to a conventional commit.

2024-12-19 15:01 UTC, Kha1r0 commented on visual-debugger/src/lib/components/ui/Button.svelte
> +    //call bridge to import the queries to QueryBatchOverview
add space after //

2024-12-19 16:49 UTC, MoPhliFra approved these changes
**Looks good to me**

2024-12-19 17:00 UTC, Kvnstrck commented
> PR title does not conform to a conventional commit title.

fixed

2024-12-19 17:06 UTC, D3vZro approved these changes

2024-12-20 10:09 UTC, Kvnstrck commented on visual-debugger/src/lib/components/ui/Button.svelte
> +    //call bridge to import the queries to QueryBatchOverview
fixed

2024-12-20 10:14 UTC, Kha1r0 approved these changes

2024-12-20 10:18 UTC, merged